{
 "title": "Docker Environment Monitoring",
 "description": "Environment monigoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Host:",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   },
   {
    "name": "swap_total",
    "query": "node_memory_SwapTotal_bytes{instance=~'$server:.*'}"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{}[5m]))"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{mountpoint=\"/\",} - node_filesystem_free_bytes{mountpoint=\"/\",} )/ node_filesystem_size_bytes{mountpoint=\"/\",})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"}) / node_memory_MemTotal_bytes{job=\"node-exporter\"}) * 100"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$server:.*',job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=~'$server:.*',job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_load1{job=\"node-exporter\"}) by (instance) / count(node_cpu_seconds_total{mode=\"system\",job=\"node-exporter\"}) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[10s])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[10s])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$__range])) * 100)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{}) by (instance) / count(node_cpu_seconds_total{mode=\"system\",}) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"rootfs\",device=\".\"} - node_filesystem_free_bytes{fstype=~\"rootfs\",device=\".\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "Free memory" },
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "Total memory" },
    {
     "expr": "node_memory_MemTotal_bytes{}-(node_memory_Buffers_bytes{}+node_memory_Shmem_bytes{}+node_memory_MemFree_bytes{})",
     "legendFormat": "Used memory"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total{}[10s])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{}[10s])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\",}[10s])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",}[10s])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",}[10s])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\",}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name=~\".+\",}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Start Time per Container",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "1000*container_start_time_seconds{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Filesystem Reads per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name=~\".+\",device=~\"/dev/sda\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_fs_reads_bytes_total{name=~\".+\",device=~\"/dev/sdb\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_fs_reads_bytes_total{name=~\".+\",device=~\"/dev/sdc\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_fs_reads_bytes_total{name=~\".+\",device=~\"/dev/sdd\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Filesystem Writes per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_writes_bytes_total{name=~\".+\",device=~\"/dev/sda\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_fs_writes_bytes_total{name=~\".+\",device=~\"/dev/sdb\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_fs_writes_bytes_total{name=~\".+\",device=~\"/dev/sdc\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_fs_writes_bytes_total{name=~\".+\",device=~\"/dev/sdd\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage Overview",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{name!=\"\",}[10s])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{name!=\"\",}-container_memory_working_set_bytes{name!=\"\",}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max(container_memory_working_set_bytes{name=~\".+\",})\r by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{name=~\".+\",}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}